services:
  web:
    image: apptizr-web
    build:
      context: web
    volumes:
      - ./web/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
  
  app:
    image: apptizr-app
    build: 
      context: src
    ports:
      - 8501:8501
      - 7860:7860
    