services:
  web:
    image: apptizr-web
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" 