[supervisord]
nodaemon=true

[program:streamlit]
command=streamlit run streamlit_app.py
autostart=true
autorestart=true
stderr_logfile=/var/log/streamlit.err.log
stdout_logfile=/var/log/streamlit.out.log

# [program:gradio]
# command=python gradio_app.py
# autostart=true
# autorestart=true
# stderr_logfile=/var/log/gradio.err.log
# stdout_logfile=/var/log/gradio.out.log
